#!/usr/bin/python2
# -*- coding: cp1252 -*-
from bs4 import BeautifulSoup
import os
import datetime
import urllib2
import tpb2rss

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
	execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
	pass

def feed_generator(path_info):
	try:
		xml = tpb2rss.xml_from_url(path_info)
		return xml
	except:
		return None

def main_body_generator(xml):
	html = "<!DOCTYPE html>"
	html += "<html lang=\"en\">"
	html += "<head>"
	html += "\t<meta charset=\"utf-8\" />"
	html += "\t<title>TPB2RSS - A RSS feed generator for ThePirateBay</title>"
	html += "\t<style type=\"text/css\">"
	html += "\t\tbody {"
	html += "\t\t\twidth: 100%;"
	html += "\t\t\theight: 100%;"
	html += "\t\t\tpadding: 0 0 0 0;"
	html += "\t\t\tmargin: 0 0 0 0;"
	html += "\t\t\tbackground: #4E818D; "
	html += "\t\t\tcolor: #fff;"
	html += "\t\t\tfont: 16px sans-serif; "
	html += "\t\t\tposition: absolute;"
	html += "\t\t}\n"
	html += "\t\t.background {"
	html += "\t\t\theight: 100%;"
	html += "\t\t\twidth: 100%;"
	html += "\t\t\tbackground-image: -ms-radial-gradient(center, ellipse farthest-corner, #85DCF2 0%, #5B97A6 100%);"
	html += "\t\t\tbackground-image: -moz-radial-gradient(center, ellipse farthest-corner, #85DCF2 0%, #5B97A6 100%);"
	html += "\t\t\tbackground-image: -o-radial-gradient(center, ellipse farthest-corner, #85DCF2 0%, #5B97A6 100%);"
	html += "\t\t\tbackground-image: -webkit-gradient(radial, center center, 0, center center, 498, color-stop(0, #85DCF2), color-stop(1, #5B97A6));"
	html += "\t\t\tbackground-image: -webkit-radial-gradient(center, ellipse farthest-corner, #85DCF2 0%, #5B97A6 100%);"
	html += "\t\t\tbackground-image: radial-gradient(ellipse farthest-corner at center, #85DCF2 0%, #5B97A6 100%);"
	html += "\t\t\tposition: absolute;"
	html += "\t\t}\n"
	html += "\t\t#container {"
	html += "\t\t\theight: 350px;"
	html += "\t\t\twidth: 900px;"
	html += "\t\t\ttop: 50%;"
	html += "\t\t\tleft: 50%;"
	html += "\t\t\tmargin-top: -175px;"
	html += "\t\t\tmargin-left: -450px;"
	html += "\t\t\tposition: absolute;"
	html += "\t\t}\n"
	html += "\t\theader {"
	html += "\t\t\twidth: 100%;"
	html += "\t\t\tmargin:0px auto;"
	html += "\t\t}\n"
	html += "\t\th1 {"
	html += "\t\t\ttext-align: center;"
	html += "\t\t\tcolor: #fff;"
	html += "\t\t\tline-height: 95px;"
	html += "\t\t\tfont-size: 95px;"
	html += "\t\t\tfont-family: \"Impact\", sans-serif;"
	html += "\t\t\tfont-weight: bolder;"
	html += "\t\t\ttext-shadow: #253e45 -1px 1px 0,"
	html += "\t\t\t#253e45 -2px 2px 0;"
	html += "\t\t\tmargin: 50px 0 0 0;"
	html += "\t\t\tdisplay: block;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon {"
	html += "\t\t\tposition: absolute;"
	html += "\t\t\tpadding: 2px 0;"
	html += "\t\t\tbackground-color: #BD4E40;"
	html += "\t\t\tbackground-image: -webkit-gradient(linear, left top, left bottom, from(rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, 0.15)));"
	html += "\t\t\tbackground-image: -webkit-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));"
	html += "\t\t\tbackground-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));"
	html += "\t\t\tbackground-image: -ms-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));"
	html += "\t\t\tbackground-image: -o-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));"
	html += "\t\t\tbackground-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));"
	html += "\t\t\t-webkit-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.5);"
	html += "\t\t\t-moz-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.5);"
	html += "\t\t\tbox-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.5);"
	html += "\t\t\tfont: 700 13px \"Helvetica Neue\", Helvetica, Arial, sans-serif;"
	html += "\t\t\tz-index: 9999;"
	html += "\t\t\tpointer-events: auto;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon a, .github-fork-ribbon a:hover {"
	html += "\t\t\tcolor: #fff;"
	html += "\t\t\ttext-decoration: none;"
	html += "\t\t\ttext-shadow: 0 -1px rgba(0, 0, 0, 0.5);"
	html += "\t\t\ttext-align: center;"
	html += "\t\t\twidth: 200px;"
	html += "\t\t\tline-height: 20px;"
	html += "\t\t\tdisplay: inline-block;"
	html += "\t\t\tpadding: 2px 0;"
	html += "\t\t\tborder-width: 1px 0;"
	html += "\t\t\tborder-style: dotted;"
	html += "\t\t\tborder-color: #fff;"
	html += "\t\t\tborder-color: rgba(255, 255, 255, 0.7);"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon-wrapper {"
	html += "\t\t\twidth: 150px;"
	html += "\t\t\theight: 150px;"
	html += "\t\t\tposition: absolute;"
	html += "\t\t\toverflow: hidden;"
	html += "\t\t\ttop: 0;"
	html += "\t\t\tz-index: 9999;"
	html += "\t\t\tpointer-events: none;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon-wrapper.fixed {"
	html += "\t\t\tposition: fixed;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon-wrapper.left {"
	html += "\t\t\tleft: 0;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon-wrapper.right {"
	html += "\t\t\tright: 0;"
	html += "\t\t}\n"
	html += "\t\t.github-fork-ribbon-wrapper.right .github-fork-ribbon {"
	html += "\t\t\ttop: 42px;"
	html += "\t\t\tright: -43px;"
	html += "\t\t\t-webkit-transform: rotate(45deg);"
	html += "\t\t\t-moz-transform: rotate(45deg);"
	html += "\t\t\t-ms-transform: rotate(45deg);"
	html += "\t\t\t-o-transform: rotate(45deg);"
	html += "\t\t\ttransform: rotate(45deg);"
	html += "\t\t}\n"
	html += "\t\t#search-box {;"
	html += "\t\t\t-webkit-border-radius: 5px;"
	html += "\t\t\t-moz-border-radius: 5px;"
	html += "\t\t\tborder-radius: 5px;"
	html += "\t\t\tbackground-color: #fff;"
	html += "\t\t\ttext-align: center;"
	html += "\t\t\twidth: 500px;"
	html += "\t\t\tleft: 50%;"
	html += "\t\t\tmargin-top: 50px;"
	html += "\t\t\tmargin-left: -250px;"
	html += "\t\t\tposition: absolute;"
	html += "\t\t}\n"
	html += "\t\t#search-text {"
	html += "\t\t\tfont-size: 14px;"
	html += "\t\t\tcolor: #ddd;"
	html += "\t\t\tborder-width: 0;"
	html += "\t\t\tbackground: transparent;"
	html += "\t\t}\n"
	html += "\t\t#search-box input[type=\"text\"] {"
	html += "\t\t\tmargin-top: 0px;"
	html += "\t\t\tmargin-left: -100px;"
	html += "\t\t\twidth: 380px;"
	html += "\t\t\tpadding: 11px 0 12px 1em;"
	html += "\t\t\tcolor: #333;"
	html += "\t\t\toutline: none;"
	html += "\t\t}\n"
	html += "\t\t#search-button {"
	html += "\t\t\tposition: absolute;"
	html += "\t\t\ttop: 0;"
	html += "\t\t\tright: 0;"
	html += "\t\t\theight: 42px;"
	html += "\t\t\twidth: 100px;"
	html += "\t\t\tfont-size: 14px;"
	html += "\t\t\tcolor: #fff;"
	html += "\t\t\ttext-transform: uppercase;"
	html += "\t\t\ttext-align: center;"
	html += "\t\t\tline-height: 42px;"
	html += "\t\t\tborder-width: 0;"
	html += "\t\t\tbackground-color: #243C42;"
	html += "\t\t\t-webkit-border-radius: 0px 5px 5px 0px;"
	html += "\t\t\t-moz-border-radius: 0px 5px 5px 0px;"
	html += "\t\t\tborder-radius: 0px 5px 5px 0px;"
	html += "\t\t\tcursor: pointer;"
	html += "\t\t}\n"
	if xml == None:
		html += "\t\t#message {"
		html += "\t\t\twidth: 260px;"
		html += "\t\t\tpadding: 8px 8px;"
		html += "\t\t\tcolor: #b94a48;"
		html += "\t\t\tbackground-color: #f2dede;"
		html += "\t\t\tborder-color: #eed3d7;"
		html += "\t\t\ttext-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);"
		html += "\t\t\tborder: 1px solid #fbeed5;"
		html += "\t\t\t-webkit-border-radius: 4px;"
		html += "\t\t\t-moz-border-radius: 4px;"
		html += "\t\t\tborder-radius: 4px;"
		html += "\t\t\tposition: relative;"
		html += "\t\t\tdisplay: block;"
		html += "\t\t}"
	html += "\t</style>"
	html += "\t<!--[if IE]><script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><![endif]-->"
	html += "\t<script>"
	html += "\tfunction changetext(){"
	html += "\t\tvar url = window.location.protocol + \"//\" + window.location.host + \"/\";"
	html += "\t\tvar input = document.getElementById(\"search-text\").value;"
	html += "\t\tvar input = input.replace(/^((http)s{0,1}:\/\/(www.){0,1}){0,1}thepiratebay\.[a-z]{1,}\//gi, \"\");"
	html += "\t\tif ((input.substring(0, 7) != \"search/\") && (input.substring(0, 7) != \"browse/\") && (input.substring(0, 5) != \"user/\") ) {"
	html += "\t\t\tvar input = \"search/\" + input"
	html += "\t\t};"
	html += "\t\tif (input.substring(7, url.length + 7) != url) {"
	html += "\t\t\tdocument.getElementById(\"search-text\").value = url + input;"
	html += "\t\t};"
	html += "\t\tif (document.getElementById(\"search-button\").innerHTML == \"Open feed\"){"
	html += "\t\t\twindow.open(document.getElementById(\"search-text\").value, \"_blank\");"
	html += "\t\t};"
	html += "\t\tdocument.getElementById(\"search-text\").focus();"
	html += "\t\tdocument.getElementById(\"search-text\").select();"
	html += "\t}"
	html += "\tfunction checkcontent(){"
	html += "\t\tvar url = window.location.protocol + \"//\" + window.location.host + \"/\";"
	html += "\t\tvar input = document.getElementById(\"search-text\").value;"
	html += "\t\tif ((input.length > url.length) && (input.substring(0, url.length ) == url)) {"
	html += "\t\t\tdocument.getElementById(\"search-button\").innerHTML = \"Open feed\";"
	html += "\t\t} else {"
	html += "\t\t\tdocument.getElementById(\"search-button\").innerHTML = \"Generate\";"
	html += "\t\t};"
	html += "\t}"
	html += "\t</script>"
	html += "</head>"
	html += "<body>"
	html += "\t<div class=\"background\"></div>"
	html += "\t<div class=\"github-fork-ribbon-wrapper right\">"
	html += "\t\t<div class=\"github-fork-ribbon\">"
	html += "\t\t\t<a href=\"https://github.com/camporez/tpb2rss\" target=\"_blank\">Fork me on GitHub</a>"
	html += "\t\t</div>"
	html += "\t</div>"
	html += "\t<div id=\"container\">"
	html += "\t\t<header>"
	html += "\t\t\t<h1>TPB2RSS</h1>"
	html += "\t\t</header>"
	html += "\t\t<div id=\"search-box\">"
	html += "\t\t<form method=\"post\" onsubmit=\"changetext(); return false;\">"
	html += "\t\t\t<input id=\"search-text\" type=\"text\" placeholder=\"Type a search term or paste a TPB link in here\" onkeyup=\"checkcontent();\" autocomplete=\"off\" autofocus required />"
	html += "\t\t\t<button type=\"submit\" id=\"search-button\">Generate</button>"
	html += "\t\t</form>"
	html += "\t</div>"
	if xml == None:
		html += "\t<div id=\"message\">Error while processing your search.</div>"
	html += "\t</div>"
	html += "</body>"
	html += "</html>"
	return html

def application(environ, start_response):
	if (( environ['PATH_INFO'] == "") or ( environ['PATH_INFO'] == "/" )):
		xml = False
	else:
		xml = feed_generator(environ['PATH_INFO'])
	if xml:
		ctype = 'text/xml'
		response_body = xml
	else:
		ctype = 'text/html'
		response_body = main_body_generator(xml)

	status = "200 OK"
	response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]

	start_response(status, response_headers)
	return [response_body]
